sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
install: npm install
before_script:
  - npm prune
script:
  - npm run echo
after_success:
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
